version: '3.7'
services:
  transaction-app:
    image: transaction-app:php-image
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: transaction-app
    environment:
      SERVICE_NAME: transaction-app
      SERVICE_TAGS: dev
    command: [ "bash", "/var/www/docker/scripts/start-app.sh" ]
    depends_on:
      - transaction-mysql
      - transaction-redis

  transaction-queue:
    image: transaction-app:php-image
    container_name: transaction-queue
    environment:
      SERVICE_NAME: transaction-queue
      SERVICE_TAGS: dev
    command: [ "bash", "/var/www/docker/scripts/start-job.sh" ]
    depends_on:
      - transaction-mysql
      - transaction-redis
      - transaction-app
      
  transaction-nginx:
    image: nginx:1.19-alpine
    container_name: transaction-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./docker/nginx/logs:/var/log/
    depends_on:
      - transaction-app
  
  transaction-mysql:
    image: mysql/mysql-server:8.0.23
    container_name: transaction-mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 9ca80cbce084b692e0b78adf4dc3f6b8883221d1fd59c86162c6f97bf4b75b8e
      MYSQL_DATABASE: transactions
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "33307:3306"

  transaction-redis:
    image: redis:6.0.10-alpine
    container_name: transaction-redis
    environment:
      AUTH: test
    ports:
      - "63790:6379"
    command: redis-server --requirepass e77cd03bbd00bb6f87cbb593e565bcaace9fc9970210c6e747eadeab90c7950d