version: '3.7'
services:
  # Accessing source code mounted on windows filesystem (/mnt) is slow on WSL2
  # Later build an image without mounting this way
  transaction-app:
    image: lukaskj/laravel-docker:7.4-fpm
    container_name: transaction-app
    environment:
      APP_NAME: TransactionBackend
      APP_ENV: local
      APP_KEY: base64:JDKwEXsMHMr3JL15GpNEOKKlX5SlIwxOaSA8UmBPtoE=
      APP_DEBUG: 'false'
      APP_URL: http://transaction-app
      # Database
      DB_CONNECTION: mysql
      DB_HOST: transaction-mysql
      DB_DATABASE: transactions
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 9ca80cbce084b692e0b78adf4dc3f6b8883221d1fd59c86162c6f97bf4b75b8e
      # redis
      REDIS_HOST: transaction-redis
      REDIS_PASSWORD: e77cd03bbd00bb6f87cbb593e565bcaace9fc9970210c6e747eadeab90c7950d
      REDIS_PORT: 6379

      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      # Other
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      TOKEN_VALID_AMOUNT: 10
      TOKEN_VALID_METRIC: days
      SERVICE_NAME: transaction-app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
    command: sh -c "/opt/wait-for-it.sh transaction-mysql:3306 -t 60 -- php artisan cache:clear && php artisan config:cache && php artisan migrate --seed --force && php-fpm"
    depends_on:
      - transaction-mysql
      - transaction-redis

  transaction-queue:
    image: lukaskj/laravel-docker:7.4-fpm
    container_name: transaction-queue
    environment:
      APP_NAME: TransactionQueue
      APP_ENV: production
      APP_KEY: base64:JDKwEXsMHMr3JL15GpNEOKKlX5SlIwxOaSA8UmBPtoE=
      APP_DEBUG: 'false'
      APP_URL: http://transaction-app

      # Database
      DB_CONNECTION: mysql
      DB_HOST: transaction-mysql
      DB_DATABASE: transactions
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 9ca80cbce084b692e0b78adf4dc3f6b8883221d1fd59c86162c6f97bf4b75b8e

      # redis
      REDIS_HOST: transaction-redis
      REDIS_PASSWORD: e77cd03bbd00bb6f87cbb593e565bcaace9fc9970210c6e747eadeab90c7950d
      REDIS_PORT: 6379

      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      # Other
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      TOKEN_VALID_AMOUNT: 10
      TOKEN_VALID_METRIC: days
      SERVICE_NAME: transaction-queue
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
    command: sh -c "/opt/wait-for-it.sh transaction-mysql:3306 -t 60 -- php artisan cache:clear && php artisan config:cache && php artisan queue:work"
    depends_on:
      - transaction-mysql
      - transaction-redis
      - transaction-app
      
  transaction-nginx:
    image: nginx:1.19-alpine
    container_name: transaction-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./docker/nginx/logs:/var/log/
    depends_on:
      - transaction-app
  
  transaction-mysql:
    image: mysql:5.7
    container_name: transaction-mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 9ca80cbce084b692e0b78adf4dc3f6b8883221d1fd59c86162c6f97bf4b75b8e
      MYSQL_DATABASE: transactions
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "33307:3306"

  transaction-redis:
    image: redis:6.0.10-alpine
    container_name: transaction-redis
    environment:
      AUTH: test
    ports:
      - "63790:6379"
    command: redis-server --requirepass e77cd03bbd00bb6f87cbb593e565bcaace9fc9970210c6e747eadeab90c7950d