version: '3.7'
services:
  transaction-php-fpm:
    image: lukaskj/laravel-docker:7.4-fpm
    container_name: transaction-php-fpm
    environment:
      SERVICE_NAME: transaction-php-fpm
      SERVICE_TAGS: dev
      DB_HOST: transaction-mysql
      DB_DATABASE: transaction-backend
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./:/var/www
      
  transaction-nginx:
    image: nginx:1.19-alpine
    container_name: transaction-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./docker/nginx/logs:/var/log/
    depends_on:
      - transaction-php-fpm
  
  transaction-mysql:
    image: mysql/mysql-server:8.0.23
    container_name: transaction-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33307:3306"