version: '3.7'
services:
  transaction-app:
    image: lukaskj/laravel-docker:7.4-fpm
    container_name: transaction-app
    environment:
      SERVICE_NAME: transaction-app
      SERVICE_TAGS: dev
      DB_HOST: transaction-mysql
      DB_DATABASE: transactions
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: user
    volumes:
      - ./:/var/www
    networks:
      - transaction-app
      
  transaction-nginx:
    image: nginx:1.19-alpine
    container_name: transaction-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./docker/nginx/logs:/var/log/
    depends_on:
      - transaction-app
    networks:
      - transaction-app
  
  transaction-mysql:
    image: mysql/mysql-server:8.0.23
    container_name: transaction-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transactions
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "33307:3306"
    networks:
      - transaction-app